- name: get nodejs repo files
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -

- name: Install nginx and node js
  ansible.builtin.dnf:
    name: 
      - '@nginx:1.26'
      -  nodejs
    state: present 
  
- name: delete html folder 
  ansible.builtin.file:
    name: /usr/share/nginx/html
    state: absent

- name: download and extract frontend
  ansible.builtin.unarchive:
    src: https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/frontend.tar.gz
    dest: /usr/share/nginx
    remote_src: true

- name: build the frontend
  ansible.builtin.shell: npm ci ; npm run build ; mv dist html
  args:
    chdir: /usr/share/nginx

- name: update nginx config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf 
  
- name: starting services
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted